services:
  puppeteer:
    #image: ghcr.io/nx-nextension/webarchive-thumbnails/puppeteer:latest
    build:
      dockerfile: ./.docker/puppeteer/Dockerfile.alpine
      context: .
    # see https://blog.jessfraz.com/post/how-to-use-new-docker-seccomp-profiles/

    security_opt:
      - seccomp=./chrome.json
    environment:
      - "CAPTCHA_SOLVER_API_KEY=${CAPTCHA_SOLVER_API_KEY}"
      - "PPTR_STEALTH=${PPTR_STEALTH}"
      - "PPTR_CAPTCHA=${PPTR_CAPTCHA}"
      - "PPTR_ANONYMIZE_UA=${PPTR_ANONYMIZE_UA}"
      - "PPTR_USER_PREFERENCES=${PPTR_USER_PREFERENCES}"
    volumes:
      #- ./conf/app/config.js:/usr/src/app/config/config.js
      - ./src:/app/src
      - ./extensions:/extensions
      - ./data:/data
    depends_on:
      - valkey
    networks:
      - backend
    restart: always
    init: true

  valkey:
    image: valkey/valkey
    restart: unless-stopped
    command: ["valkey-server", "--save", "60 1", "--loglevel", "warning"]
    volumes:
      #- ./conf/redis.conf:/usr/local/etc/valkey/valkey.conf
      - valkey_data:/data
    sysctls:
      net.core.somaxconn: 1024
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "valkey-cli", "--raw", "incr", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  valkey_data:

networks:
  backend:
    name: ${COMPOSE_NETWORK_PREFIX}-webarchive-screenshots
